# Generated by Django 4.1.7 on 2023-03-05 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.IntegerField(max_length=10)),
                ('operating_airline', models.CharField(max_length=20)),
                ('departure_city', models.CharField(max_length=20)),
                ('arrival_city', models.CharField(max_length=20)),
                ('date_of_departure', models.DateField(default=datetime.datetime)),
                ('estimated_time_of_departure', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.flight')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_app.passenger')),
            ],
        ),
    ]
