# Generated by Django 4.1.7 on 2023-03-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0002_alter_passenger_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='date_of_departure',
            field=models.DateField(),
        ),
    ]
