# Generated by Django 4.1.7 on 2023-03-05 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_app', '0003_alter_flight_date_of_departure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='flight_number',
            field=models.IntegerField(),
        ),
    ]
